### ISSUE TITLE
Make expiration not relative to construction of Transloadit object

### ISSUE THREAD

**Issue by Acconut** [ifedapoolarewaju/transloadit-java-sdk#1]
The value for the `auth.expires` is constructed when a new Transloadit object is constructed (see https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Transloadit.java#L35). However, this will probably produce an error when you want to use the Transloadit object later, in particular following example:

1. Create a new Transloadit instance when an duration of 2min.
2. Wait 5min.
3. Attempt to create an assembly.

The last operation should fail as the expiration date in the corresponding request was from 3min ago.

**Comment by ifedapoolarewaju** [comment]
@Acconut I had a wrong impression that this was how the ruby-sdk behaved. Do have any suggestions as to what the expiration should rather be relative to?

**Comment by Acconut** [comment]
Your assumption is not correct. The Ruby SDK will generate the new expiry date whenever needed, see https://github.com/transloadit/ruby-sdk/blob/403311163bd88371363976fe62ef4d57eb3673fd/lib/transloadit.rb#L122 and https://github.com/transloadit/ruby-sdk/blob/master/lib/transloadit.rb#L151.

In your case here, it should be generated in the Request#toPayload method (https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Request.java#L75) which looks like a good spot.

**Comment by ifedapoolarewaju** [comment]
@Acconut I have solved this issue [here](https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Request.java#L117-L128)
