### ISSUE TITLE
Retrieve Assembly by ID or URL

### ISSUE THREAD

**Issue by Acconut** [ifedapoolarewaju/transloadit-java-sdk#2]
Currently the only way to retrieve the full status of an Assembly is by using the `Assembly#get` method (https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Assembly.java#L53). However, it takes the Assembly ID as the parameter which is not really recommended by Transloadit. The better approach would be to use the full Assembly URL. The SDK could offer two separate methods for this, e.g. `getByID` and `getByURL`.
FYI, the reason why one should do this is that if you ask an instance, which is not responsible for executing the Assembly, it may respond with outdated information. Only the instance in the Assembly URL has the most current Assembly status.

**Comment by ifedapoolarewaju** [comment]
@Acconut retrieving assembly via url is possible [here](https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/response/AssemblyResponse.java#L29l). Since one may only need to get an assembly status via its url while it is executing.

**Comment by Acconut** [comment]
You assume that you have access to the AssemblyResponse instance which was returned after you created the assembly. However, this is not always the case, I believe. Imagine a situation where one machine creates assemblies and then hands the assembly URLs to another machine which will monitor the assembly progress. In this case, the second machine would have to fetch the assembly by its ID first to then get reload the AssemblyResponse to get the latest assembly status.

**Comment by ifedapoolarewaju** [comment]
and this

**Comment by ifedapoolarewaju** [comment]
here it is https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/main/java/com/transloadit/sdk/Transloadit.java#L79
