### ISSUE TITLE
Allow setting of custom file field names

### ISSUE THREAD

**Issue by Acconut** [ifedapoolarewaju/transloadit-java-sdk#3]
Currently the field name of a file (not to be confused with the filename) is hardcoded to `file_N` (see https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Assembly.java#L61). One may desire to set a custom field name for the sake of clarity or if the want to supply multiple a watermark and video to the encoding robot (see second example here: https://transloadit.com/docs/conversion-robots/#supplying-the-watermark-via-an-assembly-step)

**Comment by ifedapoolarewaju** [comment]
@Acconut I have addressed this issue [here](https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/AssemblyApi.java#L117-L119) please let me know what you think.

**Comment by Acconut** [comment]
LGTM :+1:
