### ISSUE TITLE
Information about supported Java versions

### ISSUE THREAD

**Issue by Acconut** [ifedapoolarewaju/transloadit-java-sdk#4]
I've noticed that you used the new lambda expression in Java (e.g. https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Steps.java#L73). However, they are only available as of Java 8 and this version is not widely supported, yet. Compilers will probably be able to compile in a way so the Java7 runtimes can still deal with it but not all people use a Java 8-compatible compiler. So you may want to reconsider using these features for supporting more Java version. Setting up Travis tests will help you there (compare https://github.com/tus/tus-java-client/blob/master/.travis.yml)

**Comment by ifedapoolarewaju** [comment]
@Acconut I have addressed this issue [here](https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Steps.java#L73)
