### ISSUE TITLE
Reconsider naming of some methods and classes

### ISSUE THREAD

**Issue by Acconut** [ifedapoolarewaju/transloadit-java-sdk#5]
The `asHash` methods should probably be called `toMap` as they return a plain map. The HashMap which you use, is just an implementation of the Map interface (e.g. https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Steps.java#L71) and you may want to change the used map implementation.

Furthermore, I would prefer it if the `Assembly` class was named `AssemblyAPI` or similar as it does not represent an actual Assembly but only provides methods for accessing information about Assemblies. This would also result in a different name for the `Transloadit#assembly` method (https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Transloadit.java#L48). Later, we may want to add a `TemplateAPI`, `BillingAPI` or `CredentialsAPI`.

Finally, you should look at which methods you really want to make public. Be aware that you can always add features but never remove them without a major version release. For example, Transloadit#getAuthData (https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Transloadit.java#L56). If you want to use it a different class while not exposing it to the public world, have a look at package-private (see https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html)

**Comment by ifedapoolarewaju** [comment]
@Acconut I have addressed these issues as well
