### ISSUE TITLE
Make BASE_URL configurable

### ISSUE THREAD

**Issue by Acconut** [ifedapoolarewaju/transloadit-java-sdk#7]
The base URL used for all request should use - by default - the HTTPS protocol for security and safety (https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Request.java#L17). Furthermore, one may want to set this to another value because they need a proxy in between or if we at Transloadit want to test the SDK against our local instances.

**Comment by ifedapoolarewaju** [comment]
@Acconut I have fixed this issue [here](https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Request.java#L33)

**Comment by Acconut** [comment]
This does not help the situation as you are not able to construct a Transloadit instance where all requests are resolved using the supplied base URL. With your fix, the user would be required to create the Request objects manually (which one actually isn't able to because the constructors are package-private) which defeats the purpose of the Transloadit SDK. Please add a method to set the base URL in the Transloadit class.

**Comment by ifedapoolarewaju** [comment]
How on earth did I miss that 😕. So stupid, before the holidays thats exactly what I had in mind, but no I got back and it completely eluded me. Thank you for spotting it @Acconut  👍🏽

**Comment by Acconut** [comment]
Absolutely no problem, we all forget stuff :)

**Comment by ifedapoolarewaju** [comment]
@Acconut I also sorted out these issues

**Comment by ifedapoolarewaju** [comment]
here it is https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/main/java/com/transloadit/sdk/Transloadit.java#L30-L34

**Comment by Acconut** [comment]
Great, but may I ask why did you use public for hostUrl (despite having an unusual name)?

```java
public String hostUrl;
```

**Comment by ifedapoolarewaju** [comment]
@Acconut are we good to close this issue?

**Comment by Acconut** [comment]
It would be nice if you would address my last comment (https://github.com/ifedapoolarewaju/transloadit-java-sdk/issues/7#issuecomment-283382899) first.

**Comment by ifedapoolarewaju** [comment]
@Acconut yes it has been addressed in the [the last PR](https://github.com/ifedapoolarewaju/transloadit-java-sdk/pull/9/files#diff-47901b3fdc7129b30d4ab7095be7b0aaR74). I added a getter instead

**Comment by Acconut** [comment]
Thank you, I wasn't aware of that. Any reason why the attribute is package-private instead of private (https://github.com/ifedapoolarewaju/transloadit-java-sdk/pull/9/files#diff-47901b3fdc7129b30d4ab7095be7b0aaR21)? You should keep access rights as restrictive as possible and since you have public getter, there is no need to set it not private. I've seen this pattern very often in your code, it may be good to review them before releasing it.

**Comment by ifedapoolarewaju** [comment]
> Any reason why the attribute is package-private instead of private 

@Acconut this is so that these attributes(though hidden from the public) can be easily accessed by the test cases. However, I have done another review to restrict attributes that are not accessed by the test suite [here](https://github.com/ifedapoolarewaju/transloadit-java-sdk/commit/2195a1386e7697f8f66b499cad92f55ee8b59049). Please let me know what you think.
